name: 'editor'

on:
  push:
    paths:
      - '05-homework/**'
      - '**/05-editor.yml'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: cd 05-homework/src

      - run: ls
      - name: Doxygen install
        run: sudo apt-get install -y doxygen

      - run: ls
      - name: Doxygen generate Doxyfile
        run: doxygen 05-homework/doc/Doxyfile
          
    # Build the HTML documentation
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: ./Doxyfile
          working-directory: 05-homework/doc
          
    # Deploy the HTML documentation to GitHub Pages
      - name: GH Pages Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html/editor
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: gh-pages

      - run: cmake 05-homework/ -D PATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Editor${{ github.run_number }}
          release_name: Editor release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./editor-0.0.${{ github.run_number }}-Linux.deb
          asset_name: editor-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package